language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"

addons:
  code_climate:
    repo_token: 11abc82dc862592a68a87222f248ae3ae9b3514f2795c374c002aa65ff58d95b

after_success:
  - npm run codeclimate


