language: node_js
node_js:
  - "8"
  - "7"
  - "6"

addons:
  code_climate:
    repo_token: 321a5ef0c7e24189f328346cd5700ea445558b7294db853312d85887d6e1bcbc6

after_success:
  - npm run codeclimate


